---
# Global configuration for production environment
# Following ethical principles of transparency and security

# System Configuration
system_timezone: "Asia/Jakarta"
system_locale: "en_US.UTF-8"

# Security Configuration (NIST SP 800-53 compliance)
security_ssh_port: 2222
security_fail2ban_enabled: true
security_automatic_updates: true
security_firewall_default_policy: deny

# Docker Configuration
docker_edition: ce
docker_version: "24.0.*"
docker_compose_version: "2.24.5"
docker_log_driver: "json-file"
docker_log_options:
  max-size: "10m"
  max-file: "3"

# Traefik Configuration
traefik_version: "3.0"
traefik_dashboard_enabled: true
traefik_dashboard_auth: "{{ vault_traefik_dashboard_auth }}"
traefik_acme_email: "admin@summitethic.com"
traefik_network_name: proxy
traefik_providers:
  - docker
traefik_entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
  # Mail-specific entrypoints
  smtp:
    address: ":25"
  submission:
    address: ":587"
  smtps:
    address: ":465"
  imap:
    address: ":143"
  imaps:
    address: ":993"
  pop3:
    address: ":110"
  pop3s:
    address: ":995"

# Mailcow Configuration
mailcow_version: "2024.01"
mailcow_install_path: /opt/mailcow-dockerized
mailcow_branch: master
mailcow_config:
  MAILCOW_HOSTNAME: "{{ mailcow_hostname }}"
  MAILCOW_PASS_SCHEME: "BLF-CRYPT"
  HTTP_PORT: 8080
  HTTP_BIND: 127.0.0.1
  HTTPS_PORT: 8443
  HTTPS_BIND: 127.0.0.1
  SMTP_PORT: 25
  SMTPS_PORT: 465
  SUBMISSION_PORT: 587
  IMAP_PORT: 143
  IMAPS_PORT: 993
  POP_PORT: 110
  POPS_PORT: 995
  SIEVE_PORT: 4190
  DOVEADM_PORT: 127.0.0.1:19991
  SQL_PORT: 127.0.0.1:13306
  SOLR_PORT: 127.0.0.1:18983
  REDIS_PORT: 127.0.0.1:7654
  SKIP_LETS_ENCRYPT: "y"
  SKIP_SOGO: "n"
  SKIP_CLAMD: "n"
  SKIP_SOLR: "n"
  ENABLE_FIDO2: "y"
  WATCHDOG_NOTIFY_EMAIL: "{{ vault_watchdog_email }}"
  WATCHDOG_NOTIFY_BAN: "y"
  WATCHDOG_EXTERNAL_CHECKS: "y"
  API_KEY: "{{ vault_mailcow_api_key }}"
  API_KEY_READ_ONLY: "{{ vault_mailcow_api_key_readonly }}"
  API_ALLOW_FROM: "127.0.0.1,::1,{{ ansible_default_ipv4.address }}"
  COMPOSE_PROJECT_NAME: "mailcowdockerized"
  DOCKER_COMPOSE_VERSION: "native"
  # Ethical data retention policy
  LOG_LINES: 9999
  MAILDIR_GC_TIME: 7200

# Monitoring Configuration (Grafana Stack)
monitoring_retention_days: 30
prometheus_version: "2.45.0"
grafana_version: "10.3.1"
loki_version: "2.9.4"
alertmanager_version: "0.26.0"

monitoring_prometheus_config:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
    external_labels:
      cluster: 'summitethic-production'

monitoring_grafana_config:
  server:
    domain: "grafana.{{ mailcow_hostname }}"
    root_url: "https://grafana.{{ mailcow_hostname }}"
  security:
    admin_password: "{{ vault_grafana_admin_password }}"
    secret_key: "{{ vault_grafana_secret_key }}"
  smtp:
    enabled: true
    host: "localhost:587"
    from_address: "monitoring@{{ mailcow_hostname }}"

monitoring_loki_config:
  auth_enabled: false
  server:
    http_listen_port: 3100
  ingester:
    lifecycler:
      address: 127.0.0.1
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
  schema_config:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

# Backup Configuration
backup_enabled: true
backup_schedule: "0 3 * * *"  # 3 AM daily
backup_retention_days: 30
backup_destinations:
  - type: local
    path: /backup/mailcow
  - type: remote
    provider: "{{ vault_backup_provider }}"
    bucket: "{{ vault_backup_bucket }}"

# Cloudflare Configuration
cloudflare_api_token: "{{ vault_cloudflare_api_token }}"
cloudflare_zone_id: "{{ vault_cloudflare_zone_id }}"
cloudflare_proxied: false  # Don't proxy mail services

# Ethical Compliance Settings
compliance_gdpr_enabled: true
compliance_data_retention_days: 365
compliance_audit_logging: true
compliance_encryption_at_rest: true
