---
all:
  children:
    mailservers:
      hosts:
        staging.mail.summitethic.com:
          ansible_host: "{{ vault_staging_host_ip }}"
          ansible_user: "{{ vault_staging_user }}"
          ansible_ssh_private_key_file: "{{ vault_staging_ssh_key }}"
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'

          # Host-specific configuration
          mailcow_hostname: staging.mail.summitethic.com
          traefik_domain: staging.mail.summitethic.com
          environment: staging

          # Resource allocation (smaller for staging)
          docker_memory_limit: 4G
          docker_cpu_limit: 2

          # Additional settings
          enable_ipv6: false
          enable_audit_logging: false

    monitoring:
      hosts:
        staging.mail.summitethic.com:
