---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false

    - name: Verify Docker is running
      ansible.builtin.systemd:
        name: docker
        state: started
      check_mode: true
      register: docker_status

    - name: Assert Docker is properly installed
      ansible.builtin.assert:
        that:
          - docker_version.rc == 0
          - docker_status.changed == false
