---
all:
  children:
    mailservers:
      hosts:
        mail.summitethic.com:
          ansible_host: "{{ vault_production_host_ip }}"
          ansible_user: "{{ vault_production_user }}"
          ansible_ssh_private_key_file: "{{ vault_production_ssh_key }}"
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'

          # Host-specific configuration
          mailcow_hostname: mail.summitethic.com
          traefik_domain: mail.summitethic.com
          environment: production

          # Resource allocation based on Contabo VPS specs
          docker_memory_limit: 5G
          docker_cpu_limit: 4

          # Additional security settings
          enable_ipv6: false
          enable_audit_logging: true

    monitoring:
      hosts:
        mail.summitethic.com:

  vars:
    # Global ansible settings
    ansible_become: true
    ansible_become_method: sudo
