---
- name: Restart ssh
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted

- name: Reload sysctl
  ansible.builtin.command: sysctl -p /etc/sysctl.d/99-security.conf
  changed_when: false
